### PR TITLE
Update cd-userprofile.yml

### PR DESCRIPTION
**Pull request by JukkaAtWork**
## Purpose

* Slot swap with healt checks

### CODE REVIEW

**Comment by TheDukeDK** [comment]
I do have one comment to your workflow. It is probably a bit easier to see what is going on if you break it up into separate jobs and use `needs` to control dependencies.

**Comment by TheDukeDK** [comment]
Same comment as I made to anssi. It would be a bit clearer as to what is happening in the workflow if you split it into more jobs and used `needs` for dependencies.

**Comment by JukkaAtWork** [comment]
> Same comment as I made to anssi. It would be a bit clearer as to what is happening in the workflow if you split it into more jobs and used `needs` for dependencies.

Done, splitted push and deploy to separate jobs.

**Comment by TheDukeDK** [comment]
Ah, forgot you are splitting the pipelines.

**Comment by JukkaAtWork** [comment]
> Ah, forgot you are splitting the pipelines.

Actually not splitting, since GHA does not support templating. Might create a new actions (hosted in the same repo) in order to achieve the same thing, but for now going with duplicate code and multiple pipelines, unfortunately.

**Review by ajarvinen — APPROVED** [review]
Cool stuff!!

**Pull request merged**
